name: "Tagparser CI"
run-name: "Tagparser CI on ${{ github.ref_name }}"

on:
  push:
    branches:
      - "feat**"
      - "fix**"
      - "hotfix**"
      - "chore**"
      - "main"
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

env:
  GO_VERSION: "1.25.0"
  LINTER_VERSION: "2.6.2"
  MODULE: "."

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Clean cache
        working-directory: ${{ env.MODULE }}
        run: go clean -modcache && go clean -testcache && go mod tidy
      - name: Install dependencies
        working-directory: ${{ env.MODULE }}
        run: go mod download
      - name: Run tests
        working-directory: ${{ env.MODULE }}
        run: go test -v -race -failfast -coverpkg=./... -covermode=atomic -coverprofile=coverage.tmp.out ./...
      - name: Exclude testdata
        working-directory: ${{ env.MODULE }}
        run: cat coverage.tmp.out | grep -v "testdata" > coverage.out
      - name: Clean temp coverage
        working-directory: ${{ env.MODULE }}
        run: rm coverage.tmp.out

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install lint
        working-directory: ${{ env.MODULE }}
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v${{ env.LINTER_VERSION }}
      - name: Run lint
        working-directory: ${{ env.MODULE }}
        run: golangci-lint run
